#[derive(Debug, PartialEq)]
pub enum Instruction {
    ADDV(usize, usize),
    ADD(usize, u8),
    ANDV(usize, usize),
    CALL(usize),
    CLS(),
    DRW(usize, usize, u8),
    INVALID(),
    JMP(usize),
    LDI(u16),
    ORV(usize, usize),
    NOP(),
    RET(),
    RND(usize, u8),
    SE(usize, u8),
    SNE(usize, u8),
    SET(usize, u8),
    SHRV(usize),
    SHLV(usize),
    SUBV(usize, usize),
    SUBNV(usize, usize),
    XORV(usize, usize),
}
