pub enum Instruction {
    ADDV(usize, usize),
    ADD(usize, u8),
    ANDV(usize, usize),
    CALL(u16),
    CLS(),
    INVALID(),
    JMP(u16),
    ORV(usize, usize),
    NOP(),
    RET(),
    SE(usize, u8),
    SNE(usize, u8),
    SET(usize, u8),
    SHRV(usize),
    SHLV(usize),
    SUBV(usize, usize),
    SUBNV(usize, usize),
    XORV(usize, usize),
    UNIMPLEMENTED(),
}

